name: deploy

on:
  push:
    branches:
      - main

env:
  GCP_REGION: ${{ secrets.GCP_REGION }}
  CACHE_CONTAINER_REGISTRY: asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/web-speed-hackathon-2021-measure
  IMAGE: asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/web-speed-hackathon-2021-measure:${{ github.sha }}

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@next
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: './scripts/leaderboard'
          preCommands: |
            yarn install --frozen-lockfile
            echo $SUPABASE_URL | wrangler secret put SUPABASE_URL
            echo $SUPABASE_ANON_KEY | wrangler secret put SUPABASE_ANON_KEY
            echo $SUPABASE_API_KEY | wrangler secret put SUPABASE_API_KEY
            echo $ALLOWED_EMAIL_DOMAIN | wrangler secret put ALLOWED_EMAIL_DOMAIN
            echo $MEASURE_SERVER_URI | wrangler secret put MEASURE_SERVER_URI
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
          ALLOWED_EMAIL_DOMAIN: ${{ secrets.ALLOWED_EMAIL_DOMAIN }}
          MEASURE_SERVER_URI: ${{ secrets.MEASURE_SERVER_URI }}
  deploy-measure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"
      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker --quiet
      - name: Pull the docker image for cache
        run: docker pull -q ${{ env.CACHE_CONTAINER_REGISTRY }}:cache | true
      - name: Build a docker image
        run: docker build --cache-from ${{ env.CACHE_CONTAINER_REGISTRY }}:cache -t ${{ env.IMAGE }} -f scripts/measure/Dockerfile .
      - name: Tag a container image
        run: docker tag ${{ env.IMAGE }} ${{ env.CACHE_CONTAINER_REGISTRY }}:cache
      - name: Push the docker image
        run: |
          docker push ${{ env.IMAGE }} &
          docker push ${{ env.CACHE_CONTAINER_REGISTRY }}:cache &
          wait
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: web-speed-hackathon-2021-measure
          image: ${{ env.IMAGE }}
          region: ${{ env.GCP_REGION }}
          env_vars: 'SUPABASE_URL=${{ secrets.SUPABASE_URL }},SUPABASE_API_KEY=${{ secrets.SUPABASE_API_KEY }},BUCKET_NAME=${{ secrets.BUCKET_NAME }}'
          flags: "--allow-unauthenticated --memory=2Gi --concurrency=1"
