name: staging deploy

on:
  workflow_run:
    workflows:
      - image build
    types:
      - completed

env:
  GCP_REGION: ${{ secrets.GCP_REGION }}
  IMAGE: asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/web-speed-hackathon-2021-measure:${{ github.sha }}

jobs:
  deploy-frontend:
    environment:
      name: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        working-directory: './scripts/leaderboard'
        run: yarn install --frozen-lockfile
      - name: Migrate
        working-directory: './scripts/leaderboard'
        run: yarn prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
      - name: Publish
        uses: cloudflare/wrangler-action@next
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: staging
          workingDirectory: './scripts/leaderboard'
          preCommands: |
            echo $SUPABASE_URL | wrangler secret put SUPABASE_URL --env staging
            echo $SUPABASE_ANON_KEY | wrangler secret put SUPABASE_ANON_KEY --env staging
            echo $SUPABASE_API_KEY | wrangler secret put SUPABASE_API_KEY --env staging
            echo $ALLOWED_EMAIL_DOMAIN | wrangler secret put ALLOWED_EMAIL_DOMAIN --env staging
            echo $MEASURE_SERVER_URI | wrangler secret put MEASURE_SERVER_URI --env staging
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_API_KEY }}
          ALLOWED_EMAIL_DOMAIN: ${{ secrets.ALLOWED_EMAIL_DOMAIN }}
          MEASURE_SERVER_URI: ${{ secrets.MEASURE_SERVER_URI }}
  deploy-measure:
    environment:
      name: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: web-speed-hackathon-2021-measure-staging
          image: ${{ env.IMAGE }}
          region: ${{ env.GCP_REGION }}
          env_vars: 'SUPABASE_URL=${{ secrets.SUPABASE_URL }},SUPABASE_API_KEY=${{ secrets.SUPABASE_API_KEY }},BUCKET_NAME=${{ secrets.BUCKET_NAME }}'
          flags: "--allow-unauthenticated --memory=2Gi --concurrency=1"
